OSGP/open-smart-grid-platform

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/networking/DlmsPushNotificationDecoder.java

SLIM-1711 Debugging showed that buffer.readableBytes() became something like 2147483641. Somehow it overflows or underflows.
Doing the math (writerIndex minus readerIndex) locally within the method yields the correct result.

SLIM-1711 Solve UnrecognizedMessageDataException

---

jenkins/pipeline/osgp-nightly-build.groovy

See the pull request pipeline script which has similar parameter for the Deploy an AWS System.

FLEX-4638 ~ Adds parameter to indicate branch for release repo.

---

integration-tests/parent-integration-tests/pom.xml
jenkins/pipeline/osgp-nightly-build.groovy
jenkins/pipeline/osgp-pr-build.groovy
osgp/protocol-adapter-iec61850/parent-pa-iec61850/pom.xml
osgp/protocol-adapter-oslp/parent-pa-oslp/pom.xml
osgp/shared/parent-shared/pom.xml

- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
- resolves GitHub security alert 'com.fasterxml.jackson.core:jackson-databind'

FLEX-4700 ~ Updates Jackson version to 2.9.8.

---

.gitignore
osgp/platform/osgp-adapter-ws-core/src/main/resources/osgp-adapter-ws-core.properties
osgp/platform/osgp-adapter-ws-publiclighting/src/main/java/org/opensmartgridplatform/adapter/ws/publiclighting/application/config/PublicLightingNotificationClientConfig.java
osgp/platform/osgp-adapter-ws-publiclighting/src/main/resources/osgp-adapter-ws-publiclighting.properties
osgp/platform/osgp-adapter-ws-shared/src/main/java/org/opensmartgridplatform/adapter/ws/shared/services/CorrelationUidTargetedNotificationService.java
osgp/platform/osgp-adapter-ws-tariffswitching/src/main/java/org/opensmartgridplatform/adapter/ws/tariffswitching/application/config/TariffSwitchingNotificationClientConfig.java
osgp/platform/osgp-adapter-ws-tariffswitching/src/main/resources/osgp-adapter-ws-tariffswitching.properties
osgp/protocol-adapter-iec61850/protocol-simulator-iec61850/WebContent/META-INF/MANIFEST.MF

FLEX-4754 ~ Uses application name 'OSGP' for notification configuration.

---

osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/AbstractMessagingConfig.java
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/jms/JmsConfiguration.java
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/jms/JmsConfigurationFactory.java
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/infra/jms/OsgpJmsTemplate.java

- add user name and password to JMS configuration properties and factory
- expose queue instance in JMS configuration class
- add initialization function for SessionAwareMessageListener
- add missing header to OsgpJmsTemplate class

OC-239 ~ Adds user name and password to JMS configuration classes.

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/housekeeping/ResponseDataCleanupJob.feature
integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/housekeeping/ResponseUrlDataCleanupJob.feature
osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/config/ResponseUrlDataCleanupScheduledJobConfig.java
osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/services/ResponseUrlDataCleanupService.java

Tests only with these tags [@SmartMetering @Housekeeping]

Fix smartmetering housekeeping

---

integration-tests/parent-integration-tests/pom.xml
osgp/platform/osgp-adapter-domain-admin/src/main/resources/logback.xml
osgp/platform/osgp-adapter-domain-core/src/main/resources/logback.xml
osgp/platform/osgp-adapter-domain-distributionautomation/src/main/resources/logback.xml
osgp/platform/osgp-adapter-domain-microgrids/src/main/resources/logback.xml
osgp/platform/osgp-adapter-domain-publiclighting/src/main/resources/logback.xml
osgp/platform/osgp-adapter-domain-smartmetering/src/main/resources/logback.xml
osgp/platform/osgp-adapter-domain-tariffswitching/src/main/resources/logback.xml
osgp/platform/osgp-adapter-ws-admin/src/main/resources/logback.xml
osgp/platform/osgp-adapter-ws-core/src/main/resources/logback.xml
osgp/platform/osgp-adapter-ws-distributionautomation/src/main/resources/logback.xml
osgp/platform/osgp-adapter-ws-microgrids/src/main/resources/logback.xml
osgp/platform/osgp-adapter-ws-publiclighting/src/main/resources/logback.xml
osgp/platform/osgp-adapter-ws-smartmetering/src/main/resources/logback.xml
osgp/platform/osgp-adapter-ws-tariffswitching/src/main/resources/logback.xml
osgp/platform/osgp-core/src/main/resources/logback.xml
osgp/platform/osgp-logging/src/main/resources/logback.xml
osgp/platform/parent-platform/pom.xml
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/resources/logback.xml
osgp/protocol-adapter-dlms/parent-pa-dlms/pom.xml
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/resources/logback.xml
osgp/protocol-adapter-iec61850/parent-pa-iec61850/pom.xml
osgp/protocol-adapter-iec61850/protocol-simulator-iec61850/src/main/resources/osgp-simulator-protocol-iec61850-logback.xml
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/resources/logback.xml
osgp/protocol-adapter-oslp/parent-pa-oslp/pom.xml
osgp/protocol-adapter-oslp/signing-server/src/main/resources/logback.xml
osgp/protocol-adapter-oslp/web-device-simulator/src/main/resources/logback.xml
osgp/shared/parent-shared/pom.xml

Use logback version provided by Spring Boot

OC-382 Update logback config

---

integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/glue/steps/ws/basicosgpfunctions/AuthorizePlatformFunctionsSteps.java
integration-tests/cucumber-tests-platform-common/src/test/resources/features/common/basic-osgp-functions/AuthorizePlatformFunctions.feature
integration-tests/cucumber-tests-platform/src/test/java/org/opensmartgridplatform/cucumber/platform/PlatformKeys.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/services/SecurityService.java

FLEX-3865 ~ Adds additional permissions for platform USER

---

osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/pom.xml
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/Iec60870ServletInitializer.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/test/java/org/opensmartgridplatform/simulator/protocol/iec60870/domain/Iec60870ASduFactoryTests.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/test/java/org/opensmartgridplatform/simulator/protocol/iec60870/server/Iec60870ASduHandlerRegistryTests.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/test/java/org/opensmartgridplatform/simulator/protocol/iec60870/server/Iec60870ConnectionEventListenerTests.java

Spring Boot 2.1.3 -> 1.5.19
JUnit 5 -> 4

OC-504 ~ Reverts to older versions in order to run in Tomcat 7

---

osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/test/resources/logback-test.xml

Enables console logging for unit testing and debugging

OC-504 ~ Updates logging configuration

---

osgp/protocol-adapter-iec60870/osgp-protocol-adapter-iec60870/src/main/java/org/opensmartgridplatform/adapter/protocol/iec60870/infra/messaging/processors/GetHealthStatusResponseEventListener.java

[@SkipTests] as it is only a small fix in code that is not being tested yet...

OC-512 ~ Adds additional condition to prevent multiple notifications

---

osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/pom.xml
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/Iec60870SimulatorApplication.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/Iec60870SimulatorConfig.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/domain/Iec60870ASduFactory.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/server/handlers/Iec60870InterrogationCommandASduHandler.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/webapp/WEB-INF/context.xml
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/test/java/org/opensmartgridplatform/simulator/protocol/iec60870/domain/Iec60870ASduFactoryTests.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/test/java/org/opensmartgridplatform/simulator/protocol/iec60870/server/Iec60870ConnectionEventListenerTest.java

[@SkipTests] as there are no tests for the simulator (yet)
- Fixes datasource issue when running in Tomcat
- Fixes sonar issues on autowired fields in Iec60870SimulatorConfig
- Updates ASDUs created in factory class
- Adds Activation Termination response to interrogation command handler
- Adds context file
- Removes commented dependency from pom

FLEX-4778 ~ Adds several fixes for simulator

---

integration-tests/parent-integration-tests/pom.xml
osgp/platform/parent-platform/pom.xml
osgp/protocol-adapter-dlms/parent-pa-dlms/pom.xml
osgp/protocol-adapter-iec60870/parent-pa-iec60870/pom.xml
osgp/protocol-adapter-iec61850/parent-pa-iec61850/pom.xml
osgp/protocol-adapter-oslp/parent-pa-oslp/pom.xml
osgp/shared/parent-shared/pom.xml
public-lighting-demo-app/parent-os-webapps/pom.xml

https://mvnrepository.com/artifact/org.springframework.data/spring-data-jpa/1.11.21.RELEASE

FLEX-4856 ~ Updates Spring Data JPA to 1.11.21.RELEASE.

---

osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/Iec60870SimulatorConfig.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/domain/Iec60870ASduFactory.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/domain/Iec60870AsduGeneratorService.java

[@SkipTests] as there are currently no integration tests for DA/IEC60870

FLEX-4824 ~ Adds periodic ASDU generation to iec60870 simulator

---

osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/config/SchedulingConfigForEventRetrievalScheduledTask.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/tasks/BaseTask.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/tasks/EventRetrievalScheduledTask.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/resources/osgp-adapter-domain-publiclighting.properties

FLEX-4917 ~ Adds hysteresis to exponential back off calculation.

---

osgp/platform/osgp-adapter-domain-core/src/main/java/org/opensmartgridplatform/adapter/domain/core/application/mapping/DomainCoreMapper.java
osgp/platform/osgp-adapter-domain-core/src/main/java/org/opensmartgridplatform/adapter/domain/core/application/services/FirmwareManagementService.java
osgp/platform/osgp-adapter-domain-core/src/test/java/org/opensmartgridplatform/adapter/domain/core/application/services/FirmwareManagementServiceTest.java
osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/FirmwareService.java
osgp/platform/osgp-adapter-ws-core/pom.xml
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementService.java
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/endpoints/FirmwareManagementEndpoint.java
osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/FirmwareVersionConverter.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/DeviceFirmwareFileRepository.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/FirmwareFileRepository.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/FirmwareModuleType.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/FirmwareVersion.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/UpdateFirmwareRequestData.java
osgp/shared/osgp-dto/src/main/java/org/opensmartgridplatform/dto/valueobjects/FirmwareVersionDto.java

FLEX-5052 ~ Fixes mapping error and comparison of firmware modules/versions.

---

console-test-result-rules
integration-tests/cucumber-tests-execution/src/main/java/org/opensmartgridplatform/cucumber/execution/AppBase.java

FLEX-5094 ~ Adds catch-all to test-suite startup.

---

osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/domain/valueobjects/DeviceMessageLog.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/services/commands/Iec61850SetScheduleCommand.java

- I changed the HashMap to a TreeMap to help sort on key
- I moved the log calls out of the body of the if-statements, thereby logging all schedule entry data attributes

FLEX-4806 ~ Logs all data attributes of schedule entries.

---

integration-tests/cucumber-tests-platform-publiclighting/src/test/resources/features/publiclighting/osgp-adapter-ws-publiclighting/ScheduleManagement/SetLightSchedule.feature

Tests legal and illegal combinations of action time, trigger window and
trigger type.

FLEX-5193 ~ Expands existing set schedule examples.

---

osgp/platform/osgp-adapter-domain-publiclighting/src/main/resources/osgp-adapter-domain-publiclighting.properties

FLEX-5230: Adapts cron expression.

---

osgp/platform/osgp-domain-core/pom.xml
osgp/platform/osgp-domain-distributionautomation/pom.xml
osgp/protocol-adapter-iec60870/osgp-iec60870/pom.xml
osgp/protocol-adapter-oslp/oslp/pom.xml

When compiling OSGP, following warning appears. This change solves it.
`[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.opensmartgridplatform:oslp:jar:5.1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-surefire-plugin @ org.opensmartgridplatform:oslp:[unknown-version], /home/dev/Sources/SmartSocietyServices/open-smart-grid-platform/osgp/protocol-adapter-oslp/oslp/pom.xml, line 109, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.opensmartgridplatform:osgp-iec60870:jar:5.1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration …

Disabled build plugins based on maven warnings

---

jenkins/pipeline/osgp-pr-build.groovy

Use m4.xlarge EC2 instance type.

---

integration-tests/cucumber-tests-platform-microgrids/src/test/java/org/opensmartgridplatform/cucumber/platform/microgrids/glue/steps/ws/microgrids/adhocmanagement/GetDataSteps.java

FLEX-5271 ~ Catch assertion errors caused by RTU system response.

---

jenkins/pipeline/osgp-pr-build.groovy

[@NoTestsPlease]
Resolves errors like `ERROR: [GitHub Commit Status Setter] Failed to update commit state on GitHub.`

Use GitHubCommitStatusSetter in pull request pipeline script.

---

osgp/platform/osgp-adapter-domain-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/domain/da/application/services/DeviceManagementService.java
osgp/platform/osgp-adapter-domain-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/domain/da/application/services/RtuDeviceService.java
osgp/platform/osgp-adapter-domain-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/domain/da/infra/jms/ws/messageprocessors/AddDeviceRequestMessageProcessor.java
osgp/platform/osgp-adapter-ws-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/ws/da/application/services/DistributionAutomationService.java
osgp/platform/osgp-adapter-ws-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/ws/da/infra/jms/DistributionAutomationRequestMessage.java
osgp/platform/osgp-adapter-ws-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/ws/da/presentation/ws/DeviceManagementEndpoint.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/AddRtuDeviceRequest.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/RtuDevice.java
osgp/protocol-adapter-mqtt/README.md
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/README.md
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/resources/mqtt_simulator_spec.json
osgp/shared/osgp-dto/src/main/java/org/opensmartgridplatform/dto/valueobjects/RtuDeviceDto.java
osgp/shared/osgp-ws-distributionautomation/src/main/java/org/opensmartgridplatform/ws/da/config/DistributionAutomationWebServiceConfig.java
osgp/shared/osgp-ws-distributionautomation/src/main/resources/DistributionAutomationAdHocManagement.wsdl
osgp/shared/osgp-ws-distributionautomation/src/main/resources/DistributionAutomationDeviceManagement.wsdl
osgp/shared/osgp-ws-distributionautomation/src/main/resources/DistributionAutomationMonitoring.wsdl
osgp/shared/osgp-ws-distributionautomation/src/main/resources/schemas/common.xsd
osgp/shared/osgp-ws-distributionautomation/src/main/resources/schemas/distributionautomation.xsd
osgp/shared/osgp-ws-distributionautomation/src/main/resources/schemas/notification.xsd
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/infra/jms/MessageType.java

SOAP Endpoint to add an RtuDevice, which can be used for MQTT communication.

OC-537 MQTT webservices

---

osgp/platform/osgp-core/src/main/resources/db/migration/V20201305090000000__Adds_manufacturers.sql
osgp/platform/osgp-core/src/main/resources/db/migration/V20201305100000000__Adds_device_models.sql

insert script for device_model and manufacturer

Slim 2439/inserts device models

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/config/ApplicationContext.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/config/MessagingConfig.java

SLIM-2257 ~ Restores properties file reading for DLMS protocol adapter.

---

osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/device/requests/SetScheduleDeviceRequest.java
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/messaging/processors/PublicLightingSetScheduleRequestMessageProcessor.java
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/messaging/processors/TariffSwitchingSetScheduleRequestMessageProcessor.java

Removes constructor with too many parameters from SetScheduleDeviceRequest

FLEX-4359-Refactor-SetScheduleDeviceRequest

---

osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/DeviceManagementService.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/OrganisationRepository.java

Orders the list of organizations on identification name.

FLEX-5413 ~ Orders organisations by identification

---

public-lighting-demo-app/web-demo-app/src/main/java/org/opensmartgridplatform/webdemoapp/web/controller/PublicLightingController.java

Application threw a NullPointerException when dimvalue was null...

Fixes internal server error in demo app

---

jenkins/pipeline/osgp-pr-build.groovy
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/validation/LongTermIntervalAndLongTermIntervalTypeValidator.java
osgp/platform/osgp-domain-core/src/test/java/org/opensmartgridplatform/domain/core/validation/LongTermIntervalAndLongTermIntervalTypeValidatorTest.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/domain/valueobjects/DaylightSavingTimeTransition.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/services/Iec61850SsldDeviceService.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/services/commands/Iec61850SetConfigurationCommand.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/services/commands/Iec61850SetScheduleCommand.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/test/java/org/opensmartgridplatform/adapter/protocol/iec61850/domain/valueobjects/DaylightSavingTimeTransitionTest.java
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/application/mapping/ConfigurationToOslpSetConfigurationRequestConverter.java
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/application/mapping/OslpGetConfigurationResponseToConfigurationConverter.java
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/networking/OslpDeviceService.java
osgp/protocol-adapter-oslp/oslp/src/main/java/org/opensmartgridplatform/oslp/OslpUtils.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/service/OslpChannelHandler.java

Need pull request to see if Sonar Qube is responding as expected

OC-615 ~ Reduces cyclomatic complexity of several methods.

---

osgp/platform/osgp-adapter-kafka-logging/src/main/java/org/opensmartgridplatform/adapter/kafka/logging/infra/kafka/in/GridMeasurementPublishedEventConsumer.java

OC-611: Fixed logging.

---

osgp/platform/osgp-adapter-domain-core/src/main/java/org/opensmartgridplatform/adapter/domain/core/application/services/FirmwareManagementService.java
osgp/platform/osgp-adapter-domain-core/src/test/java/org/opensmartgridplatform/adapter/domain/core/application/services/FirmwareManagementServiceTest.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/SsldPendingFirmwareUpdateRepository.java

Returns a list of SsldPendingFirmwareUpdates searching by device
identification and deals with multiple values being returned.

FLEX-5453 Prevent error getting firmware version with multiple pending firmware updates

---

osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/application/config/ApplicationContext.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/domain/entities/Device.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/service/OslpChannelHandler.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/web/controller/DeviceManagementController.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/resources/db/migration/V20201102092613597__Adds_firmware_version.sql
osgp/protocol-adapter-oslp/web-device-simulator/src/main/resources/i18n/messages.properties
osgp/protocol-adapter-oslp/web-device-simulator/src/main/resources/web-device-simulator.properties
osgp/protocol-adapter-oslp/web-device-simulator/src/main/webapp/WEB-INF/views/devices/edit.jsp

Flex 5516/add a field for firmware version

---

jenkins/pipeline/osgp-pr-build.groovy
runTestsAtRemoteServer.sh

[@PublicLighting @Platform @CoreAdhocManagement]

Fixes number of argument for running Cucumber tests.

---

CONTRIBUTING.md
README.md
integration-tests/README.md
osgp/platform/README.md
osgp/protocol-adapter-dlms/README.md
osgp/protocol-adapter-iec60870/README.md
osgp/protocol-adapter-iec61850/README.md
osgp/protocol-adapter-oslp/README.md
osgp/shared/README.md
public-lighting-demo-app/README.md
public-lighting-demo-app/web-demo-app/src/main/webapp/WEB-INF/views/home.jsp

OC-663 ~ Adapts links to new GXF documentation URL

---

osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/application/services/ReportingService.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/reporting/Iec61850ClientBaseEventListener.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/reporting/Iec61850ClientDaRTUEventListener.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/reporting/Iec61850ClientLMDEventListener.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/reporting/Iec61850ClientRTUEventListener.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/reporting/Iec61850ClientSSLDEventListener.java

Remove BdaEntryTime offset from iec61850 protocol adapter: https://github.com/OSGP/Documentation/issues/235

Remove BdaEntryTime offset from iec61850 protocol adapter

---

osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/services/BundleService.java
osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/endpoints/SmartMeteringBundleEndpoint.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/services/BundleService.java

Added/enriched log statements to aid in traceability.

added device identification to log messages

---

osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/ActionMapperService.java

Added a missing mapping for Set Randomisation Settings

added mapping

---

README.md
integration-tests/README.md
osgp/platform/README.md
osgp/protocol-adapter-dlms/README.md
osgp/protocol-adapter-iec60870/README.md
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/README.md
osgp/protocol-adapter-iec61850/README.md
osgp/protocol-adapter-oslp/README.md
osgp/shared/README.md
public-lighting-demo-app/README.md

- replaced JIRA link by issues page of Documentation

FDP-229 ~ Changes JIRA link.

---

osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/config/MqttClientDisabledCondition.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/config/MqttClientDisabledConfig.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/config/MqttClientEnabledCondition.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/config/MqttClientEnabledConfig.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/config/MqttConfig.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/services/MqttClient.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/services/MqttClientAdapter.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/services/SubscriptionService.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/resources/osgp-adapter-protocol-mqtt.properties
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/test/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/services/SubscriptionServiceTest.java

[@DistributionAutomation]
Signed-off-by: Kevin Smeets <kevin.smeets@cgi.com>

FDP-271 ~ Uses single broker for MQTT devices.

---

osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/services/MqttClient.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/services/MqttClientAdapter.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/java/org/opensmartgridplatform/adapter/protocol/mqtt/application/services/MqttClientAdapterFactory.java

FDP-293: Add username/password to all MQTT client creators

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/DlmsConnectionHelper.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/InvocationCounterManager.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/DlmsConnectionMessageProcessor.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/InvocationCounterManagerTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagingTestConfiguration.java

Reverts OSGP/open-smart-grid-platform#676

Revert "Save retrieved IC, dont retrieve IC during connection postprocessing"

---

osgp/pom.xml

Maven build: Disable maven-site-plugin on pom module

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/installation/CoupleMBusDevice.feature
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/mbus/DeviceChannelsHelper.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/mbus/IdentificationNumber.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/mbus/DeviceChannelsHelperTest.java

SLIM-2691 Fix cucumber tests for couple unbound g-meter

---

integration-tests/pom.xml
osgp/platform/pom.xml
osgp/protocol-adapter-dlms/pom.xml
osgp/protocol-adapter-iec60870/pom.xml
osgp/protocol-adapter-iec61850/pom.xml
osgp/protocol-adapter-mqtt/pom.xml
osgp/protocol-adapter-oslp/pom.xml
osgp/shared/pom.xml
public-lighting-demo-app/pom.xml

Signed-off-by: Kevin Smeets <kevin.smeets@alliander.com>

FDP-127 ~ Updates maven site plugin version.

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/builders/entities/DlmsDeviceBuilder.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/builders/entities/SmartMeterBuilder.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/DlmsDeviceSteps.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/support/ws/smartmetering/installation/DeviceFactory.java
osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/MBusGatewayService.java
osgp/platform/osgp-adapter-domain-smartmetering/src/test/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/mapping/InstallationMapperTest.java
osgp/platform/osgp-core/src/main/resources/db/migration/V202201101047124523__update datatype_mbus_identification_number.sql
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/SmartMeter.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/SmartMeterRepository.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/SmartMeteringDevice.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/services/ConfigurationService.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/services/DomainHelperService.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/SetDeviceLifecycleStatusByChannelCommandExecutor.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/entities/DlmsDevice.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/repositories/DlmsDeviceRepository.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/resources/db/migration/V20220110104312423__update_datatype_mbus_identification_number.sql
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/firmware/UpdateFirmwareCommandExecutorIntegrationTest.java
osgp/shared/osgp-dto/src/main/java/org/opensmartgridplatform/dto/valueobjects/smartmetering/SmartMeteringDeviceDto.java
osgp/shared/osgp-dto/src/test/java/org/opensmartgridplatform/dto/valueobjects/smartmetering/SmartMeteringDeviceDtoBuilder.java
osgp/shared/osgp-ws-smartmetering/src/main/resources/schemas/base-ws-smartmetering.xsd
osgp/shared/osgp-ws-smartmetering/src/main/resources/schemas/installation-ws-smartmetering.xsd

update datatype mbus_identification_number
Signed-off-by: Natasja Nortier <natasja.nortier@alliander.com>

SMHE-565 Update datatype for mbus identification number

---

osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/MBusGatewayService.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/entities/DlmsDevice.java
osgp/shared/osgp-ws-smartmetering/src/main/resources/schemas/base-ws-smartmetering.xsd

add leftpad mbus_identification_number
Signed-off-by: Natasja Nortier <natasja.nortier@alliander.com>

SMHE-565 Update_datatype_for_mbus_identification_number_fix_nightly

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/resources/osgp-adapter-protocol-dlms.properties

SMHE-498 Reduce timeout for jdlms to 2 minutes

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/dlmsobjectconfig/DlmsObjectConfigSmr52.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/alarm/SetAlarmNotificationsCommandExecutorTest.java

SMHE-650 Fix obis code for alarm register 2

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/utils/ByteRegisterConverter.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/networking/AlarmDecoder.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/alarm/AlarmHelperServiceTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/utils/ByteRegisterConverterTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/networking/AlarmDecoderTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/networking/DlmsPushNotificationDecoderTest.java

SMHE-642 Fix for push alarm decoding

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/functional-exceptions/FunctionalExceptionsProtocols.feature

FDP-537 ~ Fixes function exception test.

---

osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/PushSetupAlarmConverter.java
osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/PushSetupSmsConverter.java
osgp/platform/osgp-adapter-ws-smartmetering/src/test/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/PushSetupAlarmMappingTest.java
osgp/platform/osgp-adapter-ws-smartmetering/src/test/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/PushSetupSmsMappingTest.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/SendDestinationAndMethod.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/pushsetup/SetPushSetupAlarmCommandExecutor.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/pushsetup/SetPushSetupCommandExecutor.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/pushsetup/SetPushSetupSmsCommandExecutor.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/pushsetup/SetPushSetupAlarmCommandExecutorTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/pushsetup/SetPushSetupSmsCommandExecutorTest.java
osgp/shared/osgp-dto/src/main/java/org/opensmartgridplatform/dto/valueobjects/smartmetering/MessageTypeDto.java
osgp/shared/osgp-dto/src/main/java/org/opensmartgridplatform/dto/valueobjects/smartmetering/SendDestinationAndMethodDto.java

SMHE-632 Set the correct MessageType in SetPushSms and SetPushAlarm

---

super/pom.xml

Signed-off-by: Bart van der Zwet <bart.van.der.zwet@cgi.com>

Updates a number of maven plugin versions

---

osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/AbstractApplicationInitializer.java

FDP-619: lowered loglevel for NamingException

---

osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/metrics/MetricsNameService.java
osgp/shared/shared/src/test/java/org/opensmartgridplatform/shared/metrics/MetricsNameServiceTest.java

FDP-621: Standard naming service for metrics

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/installation/CoupleMBusDeviceByChannel.feature

Signed-off-by: Jaco Boon <jaco.boon@gmail.com>

Fix nighly: changed functional exception type

---

osgp/shared/osgp-dto/src/main/java/org/opensmartgridplatform/dto/valueobjects/smartmetering/AbstractPushSetupDto.java

Signed-off-by: Jaco Boon <jaco.boon@gmail.com>

Expanded validation of pushobjectlist

---

osgp/platform/osgp-core/src/main/java/org/opensmartgridplatform/core/infra/jms/domain/DefaultDomainJmsConfiguration.java
osgp/platform/osgp-core/src/main/java/org/opensmartgridplatform/core/infra/jms/protocol/DefaultProtocolJmsConfiguration.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/resources/osgp-adapter-protocol-dlms.properties
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/DefaultJmsConfiguration.java
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/JmsConfiguration.java
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/JmsConfigurationFactory.java
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/messaging/JmsPropertyNames.java

Message Priority Support is default disabled on JMS connections

Enable message priority support

---

integration-tests/cucumber-tests-platform-publiclighting/src/test/resources/features/publiclighting/basic-osgp-functions/ProtocolRequests.feature
integration-tests/cucumber-tests-platform/src/test/java/org/opensmartgridplatform/cucumber/platform/glue/steps/database/core/ProtocolInfoSteps.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/ProtocolInfoRepository.java

Signed-off-by: Jaco Boon <jaco.boon@gmail.com>

Repository method should not return more than one result

---

integration-tests/cucumber-tests-platform-publiclighting/src/test/resources/features/publiclighting/basic-osgp-functions/ProtocolRequests.feature
integration-tests/cucumber-tests-platform/src/test/java/org/opensmartgridplatform/cucumber/platform/glue/steps/database/core/ProtocolInfoSteps.java
osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/SmartMeterService.java
osgp/platform/osgp-adapter-domain-smartmetering/src/test/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/InstallationServiceTest.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/ProtocolInfoRepository.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/SmartMeteringDevice.java

Signed-off-by: Jaco Boon <jaco.boon@gmail.com>

Support for protocolVariant in shipmentfile

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/monitoring/AbstractGetPowerQualityProfileHandler.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/monitoring/GetPowerQualityProfileNoSelectiveAccessHandlerTest.java

SMHE-800 Handle missing value in power quality response

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/DlmsDeviceSteps.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/SimulatorDeviceRegister.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/cucumber-tests-platform-smartmetering.properties
integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/bundle/BundledClearAlarmRegister.feature
integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/monitoring/AlarmRegister.feature

Signed-off-by: Gerben Kroes <gerben@kroesctrl.nl>

Make sure logicalId is unique in test suite

---

osgp/protocol-adapter-dlms/osgp-protocol-simulator-dlms/simulator/dlms-device-simulator/src/main/java/org/opensmartgridplatform/simulator/protocol/dlms/server/profile/E650Profile.java

Signed-off-by: Gerben Kroes <gerben@kroesctrl.nl>

null should be used, instead of empty values

---

integration-tests/cucumber-tests-platform-distributionautomation/src/test/java/org/opensmartgridplatform/cucumber/platform/distributionautomation/glue/steps/MqttDeviceSteps.java
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/java/org/opensmartgridplatform/simulator/protocol/mqtt/SimulatorSpecPublishingClient.java
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/java/org/opensmartgridplatform/simulator/protocol/mqtt/spec/Message.java
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/java/org/opensmartgridplatform/simulator/protocol/mqtt/zip/PayloadZipper.java

FDP-764: mqtt simulator

---

osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/java/org/opensmartgridplatform/simulator/protocol/mqtt/spec/Message.java

FDP-764: Backwards compatibility for Message object (MQTT simulator)

---

integration-tests/cucumber-tests-platform-distributionautomation/src/test/java/org/opensmartgridplatform/cucumber/platform/distributionautomation/glue/steps/MqttDeviceSteps.java

FDP-764: Reverted to old constructor
