osgp/platform/osgp-core/src/main/java/org/opensmartgridplatform/core/application/config/ProtocolMessagingConfig.java

Fixes a spelling error (messageroup - messagegroup) in the value of
PROPERTY_NAME_JMS_ACTIVEMQ_MESSAGEGROUP_CACHESIZE that caused the
default value to be applied at start up if the property was set with the
correct spelling.

OC-477 Fixes JMS property name constant

---

osgp/platform/osgp-core/src/test/java/org/opensmartgridplatform/core/application/services/DeviceResponseMessageServiceTest.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/ScheduledTask.java

Truncate error message for ScheduledTask.errorLog to 255 characters (is width of database column). Add unittest for this.

OC-478 Truncate error message for ScheduledTask.errorLog

---

osgp/platform/osgp-adapter-domain-core/src/main/resources/osgp-adapter-domain-core.properties
osgp/platform/osgp-core/src/main/java/org/opensmartgridplatform/core/application/config/ApplicationContext.java
osgp/platform/osgp-core/src/main/java/org/opensmartgridplatform/core/application/config/MessagingConfig.java
osgp/platform/osgp-core/src/main/resources/osgp-core.properties
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/resources/osgp-adapter-protocol-iec61850.properties
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/resources/osgp-adapter-protocol-oslp-elster.properties
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/infra/ws/DefaultWebServiceTemplateFactory.java

* Increases the time to live for messages sent to the osgp.logging.protocol queue from 3 minutes to 1 day.
* Increases the time to live for messages sent to the ws-core.1_0.domain-core.1_0.requests queue from 10 minutes to 1 hour.
* Sets MaxConnPerRoute and MaxConnTotal for http message senders.
* Removes obsolete entries for jms.incoming.protocol.log.item.requests.queue from osgp-core.properties.
* Renames properties in osgp-core for jms.dlms.log.item.requests to jms.log.item.requests, because they are not specific for DLMS.

FLEX-4633 ~ Increases time to live and max connections

---

integration-tests/cucumber-tests-platform-microgrids/src/test/java/org/opensmartgridplatform/cucumber/platform/microgrids/glue/steps/database/core/RtuDeviceSteps.java
integration-tests/cucumber-tests-platform-microgrids/src/test/resources/features/osgp-adapter-ws-microgrids/ConnectionReestablish.feature
integration-tests/cucumber-tests-platform/src/test/java/org/opensmartgridplatform/cucumber/platform/PlatformKeys.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/RtuDevice.java

Makes sure last communication date for an RTU device is set,
preventing notifications from the communication restore mechanism,
causing failing tests:
```
org.junit.ComparisonFailure: System[1/1] type expected:<[GAS_FURNACE]>
but was:<[RTU]>
```
last communication time defaults to DateTime.now(), but could be
overridden in feature files

Fixes microgrids cucumber tests

---

osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/config/SchedulingConfigForEventRetrievalScheduledTask.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/resources/osgp-adapter-domain-publiclighting.properties

[@NoTestsPlease]
- using timezone Amsterdam makes sure we can set Dutch local times in
the cron expression
- using the scheduler to make sure no runs are performed between 08:00
and 11:59 and between 13:00 and 16:00

FLEX-4944 ~ Changes cron expression for event retrieval scheduled task.

---

integration-tests/parent-integration-tests/pom.xml
osgp/protocol-adapter-oslp/parent-pa-oslp/pom.xml
osgp/protocol-adapter-oslp/web-device-simulator/pom.xml
osgp/shared/parent-shared/pom.xml
public-lighting-demo-app/parent-os-webapps/pom.xml

Fixes CVE-2019-12814 https://nvd.nist.gov/vuln/detail/CVE-2019-12814#vulnCurrentDescriptionTitle

FLEX-4964 ~ Updates jackson-databind version to 2.9.9.1.

---

integration-tests/parent-integration-tests/pom.xml
osgp/protocol-adapter-oslp/parent-pa-oslp/pom.xml
osgp/shared/parent-shared/pom.xml

Fixes CVE-2019-14379 and CVE-2019-14439.

FLEX-4975 ~ Updates jackson-databind version to 2.9.9.2.

---

osgp/platform/osgp-adapter-ws-smartmetering/src/test/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/ListEventMappingTest.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/EventType.java
osgp/shared/osgp-ws-smartmetering/src/main/resources/schemas/sm-management.xsd

When reading the Standard Event log of the Iskra meter with Id E0033006878667817, the he-ui displays a nullpointer exception in the result of the operation.
This nullpointer is caused by the manufacturer specific code 231 the Iska meter sends in its log. This code is not known in OSGP, causing the unmarchalling to fail.
In this PR code 231 is added, solving the problem for this particular event code. In the OSGP-applications repo there is another PR for added this event code.
Please note that the (D)SMR contains more event codes not known by OSGP (the complete range for manufacturer specific codes 230-249 and other ranges reserved for future use and backwards compatibility). It should be decided whether all these codes need to be added, or that a general way of processing unknown codes …

Add event code 231

---

jenkins/pipeline/osgp-nightly-build.groovy
jenkins/pipeline/osgp-pr-build.groovy
osgp/shared/shared/src/test/java/org/opensmartgridplatform/shared/XMLGregorianCalendarToDateTimeConverterTest.java

Instead of using the 'Mailer' plugin, use the 'Email-ext' plugin. This seems to prevent problems with credentials for Gmail.

FLEX-5037 ~ Changes email step in pipeline scripts.

---

integration-tests/parent-integration-tests/pom.xml
osgp/protocol-adapter-oslp/parent-pa-oslp/pom.xml
osgp/shared/parent-shared/pom.xml

Interesting project. While going through the code, I've noticed that you're using an old version of Jackson which has some known vulnerabilities.
Fixes the following CVE's:
https://www.cvedetails.com/cve/CVE-2019-16942/
https://www.cvedetails.com/cve/CVE-2019-16943/

Bump Jackson due to known CVE's

---

osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/infra/jms/CommonRequestMessageListener.java

I found a bug related to FLEX-5070. The message processor in osgp-adapter-ws-core has not been updated to use the (new) message type defined in `org.opensmartgridplatform.shared.infra.jms.MessageType` enumeration.

FLEX-5070 ~ Replaces string by MessageType.

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/builders/entities/BaseDeviceBuilder.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/builders/entities/SecurityKeyBuilder.java

FLEX-5239 ~Fixes Cucumber 5 related nightly build issues smart metering
Fixes Cucumber step code that was broken due to the different handling
of empty data table cells with Cucumber 5 (null instead of empty
string).

FLEX-5239 ~ Fix Cucumber 5 related nightly build issues

---

integration-tests/cucumber-tests-execution/src/main/java/org/opensmartgridplatform/cucumber/execution/AppBase.java
jenkins/pipeline/osgp-nightly-build.groovy
jenkins/pipeline/osgp-pr-build.groovy

When an error is introduced in the Spring or glue context of Cucumber
tests an error is thrown preventing further tests to be executed.
This happens because the Cucumber feature runner makes the JUnit runner
abort the tests throwing a StoppedByUserException.
In such cases the Jenkins console log contains the text "End. Retval =
1", but does not contain any information on failed scenarios.
The LogParserPublisher Jenkins plugin which is activated in order to
check the log for issues with the build has configuration in a file
named console-test-rules marking this situation as an error.
By adding parameter failBuildOnError with value true, the build will be
failed when the LogParserPublisher determines an error has occurred.

OC-533 Makes build fail on error running tests

---

osgp/platform/osgp-adapter-domain-core/src/main/java/org/opensmartgridplatform/adapter/domain/core/application/services/AbstractService.java

If an entity was not found an explicit exception is thrown indicating
the type and ID, instead of the no such element exception of optional
when get is called without checking isPresent first.

FLEX-5278 ~ Explicitly deals with optional value from DB not present

---

integration-tests/cucumber-tests-platform-distributionautomation/pom.xml
integration-tests/cucumber-tests-platform-distributionautomation/src/test/java/org/opensmartgridplatform/cucumber/platform/distributionautomation/AcceptanceTests.java
integration-tests/cucumber-tests-platform-distributionautomation/src/test/resources/features/osgp-adapter-ws-distributionautomation/ReceiveMeasurementReports.feature
jenkins/pipeline/osgp-nightly-build.groovy
jenkins/pipeline/osgp-pr-build.groovy
osgp/protocol-adapter-iec60870/osgp-protocol-adapter-iec60870/pom.xml
runDistributionAutomationTestsAtRemoteServer.sh

Removes version properties for Cucumber and Spring Test from the
protocol adapter IEC60870 POM to align with versions from the super POM.
Adds a dependency to the JUnit vintage engine so the TestRunnerIT will
be executed to trigger the Cucumber component tests.
Fixes copy paste mistakes in the Cucumber tests for platform
distribution automation. Removes reference to features not present in
this project from the CucumberOptions in AcceptanceTests.
Changes the mainClass in the POM for the jar with dependencies to the
App that belongs with the distribution automation project and which is
present in the resulting jar, so that the jar can be executed.
Adapts the Jenkins pipelines to include Distribution Automation tests.

FLEX-5274 ~ Fix issues in Cucumber set up IEC 60870

---

osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/application/services/OslpLogService.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/service/RegisterDevice.java

The function `sendEventNotificationCommand()` was annotated with
`@Transactional`. This made sure the `OslpLogItem` could be saved. But
this function also creates a TCP connection to actually send an event
from the simulator to the protocol adapter. In case this TCP connection
hangs/errors/times-out the database transaction will be blocked during
that time.
The new class `OslpLogService` makes sure that the database transaction
required for saving an `OslpLogItem` is small and fast.

OC-557 ~ Prevents long running database transaction.

---

integration-tests/parent-integration-tests/pom.xml
jenkins/pipeline/osgp-dependency-check-build.groovy
osgp/protocol-adapter-iec60870/parent-pa-iec60870/pom.xml
osgp/protocol-adapter-iec61850/parent-pa-iec61850/pom.xml
super/pom.xml
super/versions-plugin-rules.xml

Configures the aggregate report of the OWASP dependency-check-maven
plugin to analyze dependencies with potential security vulnerabilities.
Configures reports about dependency and plugin updates by the
versions-maven-plugin to get insight into dependencies and plugins with
newer versions than used.
Configures a system dependency for tools.jar (com.sun:tools:1.8.0) that
caused errors when missing during the dependency analysis. Takes into
account that this jar may not be present for some Java installations on
Mac OS and uses a suggested alternative (not tested).
Replaces the FindBugs plugin, which is no longer maintained, by its
successor the SpotBugs plugin. Sets the version in the POM (which was
missing for the FindBugs plugin causing errors during dependency
analysis in the build). …

OC-526 ~ Adds dependency analysis reporting

---

super/pom.xml

To resolve errors executing the aggregate report for the OWASP
dependency check plugin a system scoped dependency to tools.jar was
added. This lead however to this dependency being added to all projects
deriving from the super POM.
As an alternative system scoped dependencies can be skipped.

OC-526 Skip system scoped dependencies in OWASP dependency check

---

super/pom.xml

Adds the dependency to javax.annotation-api in the dependency
management section of the super POM.
In many projects the dependency is transitively present, and
mostly used in for example the javax.annotation.PostConstruct
annotation.
If it is used and not declared, maven dependency analysis will
warn about a used undeclared dependency. Having the dependency
configured in the super POM simplifies fixing the maven warning
without duplication of version metadata.

FLEX-5289 Configure javax.annotation-api in super POM

---

integration-tests/cucumber-tests-core/src/test/java/org/opensmartgridplatform/cucumber/core/DateTimeHelper.java

Provides a public method giving access to the time zone used in the
DateTimeHelper for central European time (CET/CEST).

FLEX-5325 ~ Provides access to hard coded european time zone

---

integration-tests/cucumber-tests-core/src/test/java/org/opensmartgridplatform/cucumber/core/DateTimeHelper.java
integration-tests/cucumber-tests-core/src/test/java/org/opensmartgridplatform/cucumber/core/TestGetDateTime.java

Cucumber step data that has flexible date references like "tomorrow at
noon + 1 hour" is parsed returning dates in central European time zone.

FLEX-5325 Use central European time parsing flexible step dates

---

osgp/protocol-adapter-iec60870/osgp-iec60870/src/main/java/org/opensmartgridplatform/iec60870/Iec60870ServerEventListener.java
osgp/protocol-adapter-iec60870/osgp-protocol-adapter-iec60870/src/main/java/org/opensmartgridplatform/adapter/protocol/iec60870/domain/services/asduhandlers/EndOfInitializationAsduHandler.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/Iec60870SimulatorApplication.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/java/org/opensmartgridplatform/simulator/protocol/iec60870/Iec60870SimulatorConfig.java
osgp/protocol-adapter-iec60870/osgp-protocol-simulator-iec60870/src/main/resources/osgp-protocol-simulator-iec60870.properties

Updates the Iec60870ServerEventListener, so it can be created in a way
that makes sure it sends an end of initialization ASDU when the first
connection to the server is created.
The current implementation assumes a couple of things, that may need to
be modified with later insights (for instance the information object
address to be used is set to 0, and the IeCauseOfInitialization is
created with values 0 and false).
The Iec60870SimulatorConfig is extended with a boolean value
(sendEndOfInitialization) indicating whether the end of initialization
ASDU is sent when a first connection is established or not. This value
is used when creating an Iec60870Server as option with the server event
listener.
A client ASDU handler (EndOfInitializationAsduHandler) is added, mainly
to prevent errors …

FLEX-5297 Send end of initialization ASDU on first connection

---

osgp/platform/osgp-core/src/main/java/org/opensmartgridplatform/core/application/services/DeviceNetworkAddressCleanupService.java
osgp/platform/osgp-core/src/main/java/org/opensmartgridplatform/core/application/services/DeviceRegistrationMessageService.java
osgp/platform/osgp-core/src/main/resources/osgp-core.properties
osgp/platform/osgp-core/src/test/java/org/opensmartgridplatform/core/application/services/DeviceNetworkAddressCleanupServiceTest.java
osgp/platform/osgp-core/src/test/java/org/opensmartgridplatform/core/application/services/DeviceRegistrationMessageServiceTest.java

Upon device registration, the IP address of the registered device is
removed in the database for other devices where it is configured (with
the exception of the loopback address - localhost / 127.0.0.1).
These changes allow to either configure that such clean up should never
be performed (allowing multiple devices to share any network address),
or to configure a comma separated list of IP addresses or IP address
ranges that may be shared (for instance
"192.168.0.1,192.168.1.12-192.168.2.103" to allow sharing of 192.168.0.1
or any IP address from 192.168.1.12 to 192.168.2.103 inclusive).

FLEX-5395 Add configuration of IP addresses that may be duplicated

---

osgp/platform/osgp-adapter-kafka-distributionautomation/pom.xml

Deployment of osgp-adapter-kafka-distributionautomation failed
with an error creating bean with name "kafkaProducerConfig",
cause by ClassNotFoundException with class
com.fasterxml.jackson.annotation.JsonView.
Adding jackson-databind to the dependencies makes the class
available, so that context initialization succeeds on deployment
in a servlet container.

OC-606 Resolve context initialization issues adapter DA kafka

---

osgp/protocol-adapter-oslp/oslp/src/main/java/org/opensmartgridplatform/oslp/OslpDecoder.java

The OSLP decoder update makes sure all bytes are received when decoding incoming messages. This resolves the IllegalArgumentException when validating the message.

FLEX-5443 ~ Fixes signature and security key exceptions for OSLP.

---

osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/config/SchedulingConfigForDeviceConnection104LmdScheduledTask.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/services/AdHocManagementService.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/tasks/BaseTask.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/tasks/DeviceConnection104LmdScheduledTask.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/application/tasks/DeviceConnectionScheduledTask.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/java/org/opensmartgridplatform/adapter/domain/publiclighting/infra/jms/core/messageprocessors/PublicLightingGetLightSensorStatusResponseMessageProcessor.java
osgp/platform/osgp-adapter-domain-publiclighting/src/main/resources/osgp-adapter-domain-publiclighting.properties
osgp/platform/osgp-adapter-domain-shared/src/main/java/org/opensmartgridplatform/adapter/domain/shared/GetLightSensorStatusResponse.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/LightMeasurementDeviceRepository.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/LightSensorStatus.java

Makes sure connections are kept active for the light measurement devices
with protocol IEC 60870-5-104.
Adds DeviceConnection104LmdScheduledTask, a scheduled task that ensures
connections with (the gateways of) the IEC 60870-5-104 light measurement
devices.
Changes may probably be required when requests to the IEC 60870-5-104
light measurement devices will be handled from the web service layer.
This has not been addressed for FLEX-5300 since another item already is
on the backlog to make sure the correlation UID is kept between request
and response (FLEX-5349), which needs to be dealt with before the web
service responses can be matched with requests at all.

FLEX-5300 Add 60870-5-104 LMD connection monitoring

---

osgp/platform/osgp-core/src/main/java/org/opensmartgridplatform/core/application/services/EventNotificationMessageService.java

Events received from the IEC 61850 light measurement simulator are sent to osgp-core as lists, containing exactly one event. The old code rejected those without checking the contents of the list.

FLEX-5428 ~ Fixes list containing one event

---

osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/networking/ChannelCache.java
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/main/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/networking/ChannelCacheEntry.java
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/test/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/networking/ChannelCacheTest.java
osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/src/test/java/org/opensmartgridplatform/adapter/protocol/oslp/elster/infra/networking/ControlledClock.java

With FLEX-5537 a ChannelCache was introduced as a replacement of a map
of channels.
The unit tests simulated a delay for the expiration time of the cache in
a way that was sensitive to timing issues when the tests were executed
using multiple threads under heavy load.
This changes the ChannelCache to depend on a Clock (by default just the
system clock) that can be controlled during the unit tests. This way
delays (passing of time) can be simulated in the tests without actually
resorting to sleeping or delayed execution with an executor.

Fixes timing issues in ChannelCache tests

---

osgp/protocol-adapter-oslp/web-device-simulator/pom.xml
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/application/config/ApplicationContext.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/application/services/DeviceManagementService.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/service/OslpChannelHandler.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/web/controller/DelayRequest.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/java/org/opensmartgridplatform/webdevicesimulator/web/controller/DeviceManagementController.java
osgp/protocol-adapter-oslp/web-device-simulator/src/main/resources/i18n/messages.properties
osgp/protocol-adapter-oslp/web-device-simulator/src/main/resources/web-device-simulator.properties
osgp/protocol-adapter-oslp/web-device-simulator/src/main/webapp/WEB-INF/views/devices/list.jsp
osgp/protocol-adapter-oslp/web-device-simulator/src/test/java/org/opensmartgridplatform/webdevicesimulator/Assertions.java
osgp/protocol-adapter-oslp/web-device-simulator/src/test/java/org/opensmartgridplatform/webdevicesimulator/DeviceSimulatorIT.java
osgp/protocol-adapter-oslp/web-device-simulator/src/test/java/org/opensmartgridplatform/webdevicesimulator/OslpEnvelopeAssert.java
osgp/protocol-adapter-oslp/web-device-simulator/src/test/java/org/opensmartgridplatform/webdevicesimulator/OslpTestHandler.java
osgp/protocol-adapter-oslp/web-device-simulator/src/test/java/org/opensmartgridplatform/webdevicesimulator/TestConfig.java
osgp/protocol-adapter-oslp/web-device-simulator/src/test/resources/web-device-simulator-test.properties

When the OSLP web device simulator simulates a reboot a configurable
delay in seconds is applied before the device registration messages are
sent. During this delay the Netty channel for new requests will be
disconnected by the OlspChannelHandler.
The delay has a default value from configuration (reboot.delay.seconds)
and can be changed from the devices page in the web-device-simulator.
Fixes a number of warnings in the DeviceManagementController.
The general RequestMapping with a method is replaces by GetMapping or
PostMapping.
Some checks are done in the API methods that return a response for a
bad request in case there is something wrong with the provided data.
Some of the methods that were altering state have been renamed from get
to set.
The random for generating bytes is placed in a …

FLEX-5474 Add reboot behavior to the OSLP web device simulator

---

osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/application/services/DeviceRegistrationService.java
osgp/protocol-adapter-iec61850/osgp-protocol-adapter-iec61850/src/main/java/org/opensmartgridplatform/adapter/protocol/iec61850/infra/networking/Iec61850ChannelHandlerServer.java

When the IEC 61850 protocol adapter received a registration message from an unknown device, it processed the registration message anyway. Component osgp-core also created a new record for it in the osgp_core.device table. In the new situation, the registration message is not processed.

FLEX-5628 ~ Don't add device during registration

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/resources/osgp-adapter-protocol-dlms.properties

device.ping.size=0 is not always resulting in an echo reply.
Therefore setting the default to device.ping.size=1

OC-718 ~ Default ping size to 1

---

osgp/platform/osgp-adapter-ws-core/src/test/java/org/opensmartgridplatform/adapter/ws/core/application/mapping/DeviceConverterTest.java
osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/CosemDateTimeConverter.java
osgp/platform/osgp-adapter-ws-smartmetering/src/main/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/CosemTimeConverter.java
osgp/platform/osgp-adapter-ws-smartmetering/src/test/java/org/opensmartgridplatform/adapter/ws/smartmetering/application/mapping/CosemDateConverterTest.java
osgp/platform/osgp-domain-core/src/test/java/org/opensmartgridplatform/domain/core/valueobjects/smartmetering/SetRandomisationSettingsRequestDataTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/configuration/service/GetConfigurationObjectService.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/configuration/service/ProtocolServiceLookup.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/dlmsobjectconfig/DlmsObjectConfigConfiguration.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/misc/FindEventsCommandExecutorTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/monitoring/GetPowerQualityProfileCommandExecutorTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/monitoring/GetPowerQualityProfileNoSelectiveAccessHandlerTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/commands/monitoring/GetPowerQualityProfileSelectiveAccessHandlerTest.java

Adds some missing license headers, moves license headers to the top of
the file where they were added as documentation on the class instead of
the file.
Some of these modified files had Windows style line endings (carriage
return plus linefeed), these are fixed as well.

Fixes license headers and line endings

---

osgp/shared/osgp-ws-admin/src/main/resources/DeviceManagement.wsdl

Fixes the operation name in the admin device management WSDL to match
the name defined for port type DeviceManagementPort.

SLIM-1883 ~ Fixes device management operation name

---

osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/config/AbstractOsgpSchedulerConfig.java
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/application/scheduling/OsgpScheduler.java
osgp/shared/shared/src/test/java/org/opensmartgridplatform/shared/application/config/scheduling/OsgpSchedulerTest.java

The clear method on the scheduler, causes the triggers to be deleted in quartz.
When clearing the scheduler on shutdown, this causes quartz triggers to be removed when the application is stopped.
In kubernetes, the Rolling Update strategy first starts new instances, and the removes instances.
And because removing of an instances deletes the triggers, they are gone in the database, until a new instance is started.
This changes clears the triggers on startup, and then creates the new triggers in the scheduler based on the property files
Clearing of the triggers is required because if a trigger is removed in the application, you also want to deleted it from the database.

Clear scheduler on startup and not on shutdown

---

integration-tests/cucumber-tests-platform-distributionautomation/src/test/java/org/opensmartgridplatform/cucumber/platform/distributionautomation/PlatformDistributionAutomationKeys.java
integration-tests/cucumber-tests-platform-distributionautomation/src/test/java/org/opensmartgridplatform/cucumber/platform/distributionautomation/glue/steps/MqttDeviceSteps.java
integration-tests/cucumber-tests-platform-distributionautomation/src/test/java/org/opensmartgridplatform/cucumber/platform/distributionautomation/glue/steps/database/FeederSteps.java
integration-tests/cucumber-tests-platform-distributionautomation/src/test/resources/features/low-voltage/ProcessLowVoltageMessage.feature
osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/ScadaMeasurementPublishedEventConverter.java
osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/domain/entities/Feeder.java
osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/infra/kafka/out/LowVoltageMessageProducer.java
osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/java/org/opensmartgridplatform/adapter/kafka/da/infra/mqtt/in/ScadaMeasurementPayload.java
osgp/platform/osgp-adapter-kafka-distributionautomation/src/main/resources/db/migration/V20210604150958175__Add_asset_label_to_feeder.sql
osgp/platform/osgp-adapter-kafka-distributionautomation/src/test/java/org/opensmartgridplatform/adapter/kafka/da/application/mapping/ScadaMeasurementPublishedEventConverterTest.java

Adds field assetLabel to the Feeder entity. This can contain a label
with identification details for the feeder.
When a ScadaMeasurementPayload is processed and a feeder is found, the
asset label of the feeder is used to enrich the
ScadaMeasurementPublishedEvent with a name of type 'functieplaatslabel'.
[@DistributionAutomation]

FDP-48 Include feeder asset label in event message

---

integration-tests/cucumber-tests-core/src/test/java/org/opensmartgridplatform/cucumber/core/ReadSettingsHelper.java
integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/glue/steps/ws/basicosgpfunctions/AuthorizePlatformFunctionsSteps.java
integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/glue/steps/ws/core/firmwaremanagement/AddFirmwareSteps.java
integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/glue/steps/ws/core/firmwaremanagement/AddOrChangeFirmwareSteps.java
integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/glue/steps/ws/core/firmwaremanagement/FirmwareSteps.java
integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/support/ws/core/CoreFirmwareManagementClient.java
integration-tests/cucumber-tests-platform-common/src/test/resources/features/common/osgp-adapter-ws-core/FirmwareManagement/AddFirmware.feature
integration-tests/cucumber-tests-platform-common/src/test/resources/features/common/osgp-adapter-ws-core/FirmwareManagement/AddOrChangeFirmware.feature
integration-tests/cucumber-tests-platform-common/src/test/resources/features/common/osgp-adapter-ws-core/FirmwareManagement/ChangeFirmware.feature
integration-tests/cucumber-tests-platform/src/test/java/org/opensmartgridplatform/cucumber/platform/glue/steps/database/core/FirmwareFileSteps.java
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/mapping/FirmwareConverter.java
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareFileRequest.java
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementService.java
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/endpoints/FirmwareManagementEndpoint.java
osgp/platform/osgp-adapter-ws-shared-db/src/main/java/org/opensmartgridplatform/adapter/ws/shared/db/domain/repositories/writable/WritableFirmwareFileRepository.java
osgp/platform/osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/FirmwareFile.java
osgp/shared/osgp-ws-core/src/main/resources/FirmwareManagement.wsdl
osgp/shared/osgp-ws-core/src/main/resources/schemas/firmwaremanagement.xsd

The existing implementation of two endpoints in FirmwareManagement are not compliant with the datamodel of the Core database. These endpoints (AddFirmwareRequest and ChangeFirmwareRequest) differ from this datamodel on two major points
- The Identification column was added as mandatory, unique and user-defined column. 
The current implementation uses either the Id column (internal database key) or a combination of Firmware's filename and related devicemodel's code to uniquely identifythe Firmware
- The current implementation assumes an one-on-one relationbetween Firmware and DeviceModel. The datamodel in the Core database has a many-to-many relation between Firmware and DeviceModel.
SMHE needs an endpoint to synchronize between it's own database and the database on the GXF platform.
- …

SLIM-2987-HSTN-an-uploaded-FW-file-in-SMHE-must-also-be-send-to-GXF

---

osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/mapping/FirmwareConverter.java
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/mapping/FirmwareManagementMapper.java
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/mapping/FirmwareModuleDataConverter.java
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/services/FirmwareManagementService.java
osgp/shared/osgp-ws-core/src/main/resources/schemas/firmwaremanagement.xsd

Added ModuleVersionActive as one of moduleVersiontypes in ModuleVersionData for use with SmartMetering.
This additional versiontype needed some adeption in convertors since they reused the Func(tional) moduleVersiontype for Active moduleVersiontype in use with SmartMetering. A follow-up story will be defined to tackle this.

Slim 2987 Added ModuleVersionActive as one of moduleVersiontypes in ModuleVersionData

---

osgp/platform/osgp-adapter-ws-core/pom.xml
osgp/platform/osgp-adapter-ws-core/src/main/java/org/opensmartgridplatform/adapter/ws/core/application/config/ApplicationContext.java

Removes the dependency to osgp-adapter-domain-logging and the imported
ReadOnlyLoggingConfig from osgp-adapter-ws-core and its
ApplicationContext.
This dependency and imported configuration provided access to the
database with logging information that the web service operations from
WS core do not need access to.

FDP-113 Remove dependency to domain-logging from ws-core

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/DlmsConnectionHelper.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/InvocationCounterManager.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/DlmsConnectionMessageProcessor.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/InvocationCounterManagerTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagingTestConfiguration.java

This PR fixes a major bug: since the merge of https://github.com/OSGP/open-smart-grid-platform/pull/652
no connection is possible with smart meters using the IC. 
The retrieved IC is never saved to the dlms_device table which leads to always failing connections since the stored IC always has the incorrect value '0'. 
The IC is saved after retrieving. Within the connection post processing, the init IC is removed since this is already in place in DlmsConnectionHelper.createConnectionForDevice().

Save retrieved IC, dont retrieve IC during connection postprocessing

---

osgp/protocol-adapter-dlms/osgp-jasper-interface/src/main/java/org/opensmartgridplatform/adapter/protocol/jasper/config/JasperWirelessConfig.java
osgp/protocol-adapter-dlms/osgp-jasper-interface/src/main/java/org/opensmartgridplatform/adapter/protocol/jasper/infra/ws/JasperWirelessSmsClient.java
osgp/protocol-adapter-dlms/osgp-jasper-interface/src/main/resources/jasper-interface.properties
osgp/protocol-adapter-dlms/osgp-jasper-interface/src/test/java/org/opensmartgridplatform/adapter/protocol/jasper/infra/ws/JasperWirelessSmsClientTest.java
osgp/protocol-adapter-dlms/osgp-jasper-interface/src/test/java/org/opensmartgridplatform/adapter/protocol/jasper/infra/ws/JasperWirelessTestConfig.java

This PR adds a validity period (tpvp) value to the jasper wireless API, default value should be 0 = 5 minutes
The formula is: (validityPeriod + 1) * 5 minutes
Signed-off-by: Gerben Kroes <gerben@kroesctrl.nl>

SLIM-3056 Add validity period to the Jasper API call for wake-up by SMS

---

osgp/shared/osgp-ws-smartmetering/src/main/resources/SmartMeteringManagement.wsdl
osgp/shared/osgp-ws-smartmetering/src/main/resources/schemas/bundle-ws-smartmetering.xsd
osgp/shared/osgp-ws-smartmetering/src/main/resources/schemas/management-ws-smartmetering.xsd

As a PO i want smhe to clear the mbus status, so the alarms are cleared via the E-meter to the G-meter.
After this the 5.1 G-meter is ready to raise new alarms.
5.0 E-meters clears the status by itself, in production we found out that sometimes the alarms/event where already cleared before the headend started an event readout.
The clear action works with a mask, the headend first has to read out the bits. Make a mask to clear only the raised bits, and send this to the E-meter. After this the reset alarm method can be started.

SLIM-2065 Clear mbus status xsd implementation

---

osgp/protocol-adapter-dlms/osgp-protocol-simulator-dlms/simulator/dlms-device-simulator-starter/pom.xml
osgp/protocol-adapter-dlms/osgp-protocol-simulator-dlms/simulator/dlms-device-simulator-starter/src/main/java/org/opensmartgridplatform/simulatorstarter/protocol/dlms/starter/Starter.java
osgp/protocol-adapter-dlms/osgp-protocol-simulator-dlms/simulator/dlms-device-simulator/pom.xml
osgp/protocol-adapter-dlms/osgp-protocol-simulator-dlms/simulator/dlms-device-simulator/src/main/java/org/opensmartgridplatform/simulator/protocol/dlms/server/DeviceServer.java
osgp/protocol-adapter-dlms/osgp-protocol-simulator-dlms/simulator/startSimulatorStarter.sh

Database functionality and resources were removed from the simulator project since they were not used anymore. 
The datasource related dependencies were removed so spring boot does not try to configure them.

excluded springboot autoconfigure from starter

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringconfiguration/ReceivedAlarmNotificationsSteps.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/ws/smartmetering/smartmeteringmonitoring/SystemEventSteps.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/support/ws/smartmetering/configuration/SmartMeteringConfigurationClient.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/ReceiveAlarmNotifications.feature

An earlier improvement filtered the notifications by type to make sure a
system event was handled. Before filtering it turned out a push
notification alarm could make the test fail.
This updates the Cucumber test dealing with push notification alarms to
not only check if the pushed alarm ends up in the logging database, but
also check a notification was sent and the push notification alarm
response can be retrieved.
By including retrieval of the pushed alarm message, its notification
should no longer be able to break other test cases.
Processing of the pushed alarms still had some notification check issues
due to the way pushed alarms are treated in the
PushNotificationAlarmMessageProcessor from core. When two alarms by the
same devices arrive in the queues at about the same time, …

FDP-109 Improve test robustness notifications

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/services/DomainHelperService.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/threads/RecoverKeyProcess.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/DlmsConnectionHelper.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/DlmsConnectionManager.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/InvocationCounterManager.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/DeviceRequestMessageProcessor.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/application/services/DomainHelperServiceTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/application/threads/RecoverKeyProcessTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/entities/DlmsDeviceBuilder.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/DlmsConnectionHelperTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/DlmsConnectionManagerTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/InvocationCounterManagerTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/DeviceRequestMessageListenerIT.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/infra/messaging/MessagingTestConfiguration.java

If the invocationcounter is out of sync the DlmsConnectionManager tries to close connections that are not opened yet, this is caused by: the change in DlmsConnectionFactory where the DlmsConnectionManager is now used with try-with-resources in the method 
createAndHandleConnectionWithSecurityLevel that closes the connections.
Second issue was that when the invocationcounter was not in sync the value was not saved to the database. This is caused by a change in the DeviceRequestMessageProcessor-> processMessageTasks(). in the finally block is fresh device retrieved from the database. Before this changes the updated device with updated invocationCounter value was used, and therefor saved
```    } finally {
final DlmsDevice device = this.domainHelperService.findDlmsDevice(messageMetadata); …
```

Fixed 2 connection issues in the protocol adapter.

---

osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/infra/networking/ping/CommandExecutor.java
osgp/shared/shared/src/main/java/org/opensmartgridplatform/shared/infra/networking/ping/Pinger.java

Always close executor services to allow reclamation of its resources.
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html

Always close a executor service

---

osgp/platform/osgp-core/src/main/resources/db/migration/V20211007131424000__deletes_CDMA_specific_protocol_info.sql

There are 3 records SMR_CDMA (5.1) SMR_CDMA (5.0.0) en DSMR_CDMA (4.2.2) created by flyway. By SMHE are there a number of protocols created SMR_GPRS en SMR_LTE_M by hand, if they exist the records created by SMHE will should not be removed by this flyway script

Remove CDMA specific protocol from GXF

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/java/org/opensmartgridplatform/cucumber/platform/smartmetering/glue/steps/database/device/DlmsDeviceSteps.java
integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/configuration/ReplaceKeys.feature
osgp/platform/osgp-secret-management/src/integration-test/java/org/opensmartgridplatform/secretmanagement/application/SoapServiceSecretManagementIT.java
osgp/platform/osgp-secret-management/src/main/java/org/opensmartgridplatform/secretmanagement/application/services/SecretManagementService.java
osgp/platform/osgp-secret-management/src/test/java/org/opensmartgridplatform/secretmanagement/application/services/SecretManagementServiceTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/services/SecretManagementService.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/threads/RecoverKeyProcess.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/factories/Hls5Connector.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/application/services/SecretManagementServiceTest.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/test/java/org/opensmartgridplatform/adapter/protocol/dlms/application/threads/RecoverKeyProcessTest.java

The recover key process is changed to match the situations it will occur. At this moment the code always expect two new keys, however this is never the case since keys are replaced one by one.
The implementation is done based on the design: https://alliander.atlassian.net/wiki/spaces/HOUS/pages/2956266827/Replace+Key+process
Nightly: https://ci.opensmartgridplatform.org/view/Nightly/job/OSGP_open-smart-grid-platform_nightly/1468/cucumber-html-reports/overview-features.html

SMHE-227 change recover key process

---

osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/application/config/DlmsConfig.java

Either the throttlingService or the throttling client in the
ThrottlingClientConfig is available. The autowired bean parameter for
the TrottlingService should not be required.

FDP-497 Make throttling service dependency in recover key process non-required

---

super/pom.xml

Due to Logback issue LOGBACK-191 the version of Logback is updated to
1.2.8.
This should prevent remote code execution in case the attacker has
write access to logback.xml and configuration data is reloaded by
application restart, or because scan="true" prior to the configuration
change.

Update logback version to 1.2.8

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/configuration/Firmware.feature
osgp/platform/osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/MBusGatewayService.java
osgp/protocol-adapter-dlms/osgp-protocol-adapter-dlms/src/main/java/org/opensmartgridplatform/adapter/protocol/dlms/domain/entities/DlmsDevice.java

revert leftpadding with zeros of mbus identification number and update test data, mbus identification number with length 7 is not a valid case
Signed-off-by: Natasja Nortier <natasja.nortier@alliander.com>

SMHE-565 Update datatype for mbus identification number

---

integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/glue/steps/database/ws/NotificationWebServiceConfigurationBuilder.java
integration-tests/cucumber-tests-platform-common/src/test/java/org/opensmartgridplatform/cucumber/platform/common/support/ws/core/notification/CoreNotificationService.java
integration-tests/cucumber-tests-platform-common/src/test/resources/cucumber-tests-platform-common.properties
integration-tests/cucumber-tests-platform-common/src/test/resources/features/common/osgp-adapter-ws-core/notifications/ResendNotifications.feature
integration-tests/cucumber-tests-platform-distributionautomation/src/test/resources/cucumber-tests-platform-distributionautomation.properties
integration-tests/cucumber-tests-platform-microgrids/src/test/resources/cucumber-tests-platform-microgrids.properties
integration-tests/cucumber-tests-platform-publiclighting/src/test/resources/cucumber-tests-platform-publiclighting.properties
integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/cucumber-tests-platform-smartmetering.properties
integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/housekeeping/ResponseUrlDataCleanupJob.feature
integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/notifications/ResendNotifications.feature
integration-tests/cucumber-tests-platform/src/test/java/org/opensmartgridplatform/cucumber/platform/glue/steps/database/ws/ResponseUrlDataBuilder.java

This PR fixes 2 disabled tests, they were failing because of a NPE in the test. 
I also changed. the ports of the cucumber notification ports because a few of those were conflicting with other ports.
8090 we used for pgadmin interface
8088 was also used for a kafka project
So i added 100 to the port numbers
A link to each of the triggered nightly's tests are in the PR-comments

Enable skipped tests

---

integration-tests/cucumber-tests-platform-distributionautomation/src/test/java/org/opensmartgridplatform/cucumber/platform/distributionautomation/glue/steps/MqttDeviceSteps.java
osgp/protocol-adapter-mqtt/osgp-protocol-adapter-mqtt/src/main/resources/osgp-adapter-protocol-mqtt.properties
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/java/org/opensmartgridplatform/simulator/protocol/mqtt/Broker.java
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/java/org/opensmartgridplatform/simulator/protocol/mqtt/Client.java
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/java/org/opensmartgridplatform/simulator/protocol/mqtt/SimulatorSpecPublishingClient.java
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/java/org/opensmartgridplatform/simulator/protocol/mqtt/spec/Message.java
osgp/protocol-adapter-mqtt/osgp-protocol-simulator-mqtt/src/main/java/org/opensmartgridplatform/simulator/protocol/mqtt/spec/SimulatorSpec.java

Prevents some issues handling MQTT messages by allowing messages from
certain topics to be considered as zipped.
Instead of creating a String from the bytes, in such cases an unzip
action is done first.
Adds support to the SimulatorSpecPublischingClient to only send the
messages from a spec once, instead of continuously replaying the same
messages over and over. This should enable Cucumber tests where step
data can have a message that should be sent only once.

FDP-697 Add some support for zipped MQTT messages

---

integration-tests/cucumber-tests-platform-smartmetering/src/test/resources/features/osgp-adapter-ws-smartmetering/configuration/RecoverKeys.feature

Failing test:
https://ci.opensmartgridplatform.org/view/Nightly/job/OSGP_open-smart-grid-platform_nightly/1707/cucumber-html-reports/report-feature_145_2784502065.html
Solution: give test more seconds before timeout
Signed-off-by: Harry Middelburg <harry.middelburg@alliander.com>

Failing Test Scenario Recover keys after a (simulated) failed key change 

---

osgp/shared/osgp-ws-smartmetering/src/main/java/org/opensmartgridplatform/ws/smartmetering/config/SmartmeteringWebServiceConfig.java

Added a bean with the base schema and the correct bean name 'base-ws-smartmetering' to make the base xsd available.

base-ws-smartmetering xsd available
